import type {
  EmirateTableRow,
  FinanceReportsOverviewData,
  UserTypeTableRow,
} from "./type";

export const financeReportsOverviewMock: FinanceReportsOverviewData = {
  summaryCards: [
    {
      key: "totalRevenue",
      displayValue: "218.42M",
      iconKey: "totalRevenue",
      titleKey: "financeReportsAnalytics.summary.totalRevenue",
    },
    {
      key: "totalPayments",
      displayValue: "301,000",
      iconKey: "totalPayments",
      titleKey: "financeReportsAnalytics.summary.totalPayments",
    },
    {
      key: "totalRecharges",
      displayValue: "2000",
      iconKey: "totalRecharges",
      titleKey: "financeReportsAnalytics.summary.totalRecharges",
    },
    {
      key: "totalRefunds",
      displayValue: "2000",
      iconKey: "totalRefunds",
      titleKey: "financeReportsAnalytics.summary.totalRefunds",
    },
  ],
  revenueTrend: {
    categories: [
      "28/01 - 01/02",
      "02/02 - 08/02",
      "09/02 - 15/02",
      "16/02 - 22/02",
      "23/02 - 28/02",
    ],
    yAxisMin: -100,
    yAxisMax: 400,
    yAxisInterval: 100,
    yAxisSuffix: "M",
    series: [
      {
        name: "Revenue",
        nameKey: "financeReportsAnalytics.series.revenue",
        color: "#A0D5AB",
        values: [130, 130, 215, 250, 300],
      },
      {
        name: "Service Application Fees",
        nameKey: "financeReportsAnalytics.series.serviceApplicationFees",
        color: "#D7BC6D",
        values: [120, 120, 180, 180, 180],
      },
      {
        name: "Fines",
        nameKey: "financeReportsAnalytics.series.fines",
        color: "#FAD44F",
        values: [0, 0, 25, 28, 52],
      },
      {
        name: "Refunds",
        nameKey: "financeReportsAnalytics.series.refunds",
        color: "#FAAAA7",
        values: [-5, -5, -50, -50, -5],
      },
    ],
  },
  revenueBreakdown: {
    yAxisMin: -50,
    yAxisMax: 200,
    yAxisInterval: 50,
    yAxisSuffix: "M",
    items: [
      {
        name: "Service Application Fees",
        nameKey: "financeReportsAnalytics.series.serviceApplicationFees",
        value: 175.21,
        displayValue: "175.21M",
        color: "#A0D5AB",
      },
      {
        name: "Fines",
        nameKey: "financeReportsAnalytics.series.fines",
        value: 132.21,
        displayValue: "132.21M",
        color: "#FAD44F",
      },
      {
        name: "Refunds",
        nameKey: "financeReportsAnalytics.series.refunds",
        value: -5.32,
        displayValue: "-5.32M",
        color: "#FAAAA7",
      },
    ],
  },
  paymentsByType: {
    total: 10000,
    totalLabel: "10,000",
    legends: [
      {
        label: "Service Application Fees",
        labelKey: "financeReportsAnalytics.series.serviceApplicationFees",
        value: 7500,
        valueLabel: "7,500",
        percentageLabel: "75.00%",
        color: "#A0D5AB",
      },
      {
        label: "Fines",
        labelKey: "financeReportsAnalytics.series.fines",
        value: 2000,
        valueLabel: "2,000",
        percentageLabel: "20.00%",
        color: "#FAD44F",
      },
      {
        label: "Refunds",
        labelKey: "financeReportsAnalytics.series.refunds",
        value: 500,
        valueLabel: "500",
        percentageLabel: "5.00%",
        color: "#FAAAA7",
      },
    ],
  },
  paymentsByTypeMetric: {
    label: "Payment Failure Rate",
    labelKey: "financeReportsAnalytics.charts.paymentFailureRate",
    value: "2.4%",
    dotColor: "#F26D6D",
  },
  paymentMethodDistribution: {
    total: 300000,
    totalLabel: "300,000",
    legends: [
      {
        label: "Wallet",
        labelKey: "financeReportsAnalytics.paymentMethods.wallet",
        value: 180000,
        valueLabel: "180,000",
        percentageLabel: "60.00%",
        color: "#A0D5AB",
      },
      {
        label: "Credit / Debit Card",
        labelKey: "financeReportsAnalytics.paymentMethods.card",
        value: 120000,
        valueLabel: "120,000",
        percentageLabel: "40.00%",
        color: "#78B4FF",
      },
    ],
  },
  rechargeBreakdown: {
    categories: [
      "28/01 - 01/02",
      "02/02 - 08/02",
      "09/02 - 15/02",
      "16/02 - 22/02",
      "23/02 - 28/02",
    ],
    yAxisMin: 0,
    yAxisMax: 2500,
    yAxisInterval: 500,
    series: [
      {
        name: "Recharges",
        nameKey: "financeReportsAnalytics.summary.totalRecharges",
        color: "#D7BC6D",
        areaColor: "rgba(215, 188, 109, 0.16)",
        values: [900, 900, 1400, 1400, 2100],
      },
    ],
  },
  rechargeCount: {
    total: 200000,
    totalLabel: "200,000",
    legends: [
      {
        label: "Completed",
        labelKey: "financeReportsAnalytics.status.completed",
        value: 190000,
        valueLabel: "190,000",
        percentageLabel: "95.00%",
        color: "#A0D5AB",
      },
      {
        label: "Failed",
        labelKey: "financeReportsAnalytics.status.failed",
        value: 10000,
        valueLabel: "10,000",
        percentageLabel: "5.00%",
        color: "#FAAAA7",
      },
    ],
  },
  refundAmountByMethod: {
    total: 50520000,
    totalLabel: "50.52M",
    legends: [
      {
        label: "Wallet Refund",
        labelKey: "financeReportsAnalytics.refundMethods.walletRefund",
        value: 10010000,
        valueLabel: "10.01M",
        percentageLabel: "19.80%",
        color: "#A0D5AB",
      },
      {
        label: "Card Refund",
        labelKey: "financeReportsAnalytics.refundMethods.cardRefund",
        value: 40510000,
        valueLabel: "40.51M",
        percentageLabel: "80.20%",
        color: "#78B4FF",
      },
    ],
  },
  refundTypeDistribution: {
    total: 10000,
    totalLabel: "10,000",
    legends: [
      {
        label: "Full Refund",
        labelKey: "financeReportsAnalytics.refundTypes.fullRefund",
        value: 6500,
        valueLabel: "6,500",
        percentageLabel: "65.00%",
        color: "#A0D5AB",
      },
      {
        label: "Partial Refund",
        labelKey: "financeReportsAnalytics.refundTypes.partialRefund",
        value: 3500,
        valueLabel: "3,500",
        percentageLabel: "35.00%",
        color: "#FAD44F",
      },
    ],
  },
};

export const emirateTableMock: EmirateTableRow[] = [
  {
    id: "dubai",
    locationKey: "dubai",
    totalRevenue: "87.28M",
    totalRevenueValue: 87.28,
    transactionCount: "12,000",
    rechargeCount: "12,000",
    refundCount: "12,000",
    refundRate: "3.1%",
  },
  {
    id: "abu-dhabi",
    locationKey: "abuDhabi",
    totalRevenue: "77.28M",
    totalRevenueValue: 77.28,
    transactionCount: "8,000",
    rechargeCount: "8,000",
    refundCount: "8,000",
    refundRate: "3.1%",
  },
  {
    id: "sharjah",
    locationKey: "sharjah",
    totalRevenue: "54.28M",
    totalRevenueValue: 54.28,
    transactionCount: "6,000",
    rechargeCount: "6,000",
    refundCount: "6,000",
    refundRate: "3.1%",
  },
  {
    id: "ajman",
    locationKey: "ajman",
    totalRevenue: "32.13M",
    totalRevenueValue: 32.13,
    transactionCount: "5,000",
    rechargeCount: "5,000",
    refundCount: "5,000",
    refundRate: "3.1%",
  },
  {
    id: "ras-al-khaimah",
    locationKey: "rasAlKhaimah",
    totalRevenue: "27.28M",
    totalRevenueValue: 27.28,
    transactionCount: "4,000",
    rechargeCount: "4,000",
    refundCount: "4,000",
    refundRate: "3.1%",
  },
  {
    id: "fujairah",
    locationKey: "fujairah",
    totalRevenue: "17.28M",
    totalRevenueValue: 17.28,
    transactionCount: "1,000",
    rechargeCount: "1,000",
    refundCount: "1,000",
    refundRate: "3.1%",
  },
  {
    id: "umm-al-quwain",
    locationKey: "ummAlQuwain",
    totalRevenue: "7.28M",
    totalRevenueValue: 7.28,
    transactionCount: "800",
    rechargeCount: "800",
    refundCount: "800",
    refundRate: "3.1%",
  },
];

export const userTypeTableMock: UserTypeTableRow[] = [
  {
    id: "individual",
    userTypeKey: "individual",
    totalRevenue: "54.55M",
    totalRevenueValue: 54.55,
    transactionCount: "12,000",
    rechargeCount: "12,000",
    refundCount: "12,000",
    refundRate: "3.1%",
  },
  {
    id: "commercial",
    userTypeKey: "commercial",
    totalRevenue: "87.28M",
    totalRevenueValue: 87.28,
    transactionCount: "8,000",
    rechargeCount: "8,000",
    refundCount: "8,000",
    refundRate: "3.1%",
  },
  {
    id: "government",
    userTypeKey: "government",
    totalRevenue: "54.28M",
    totalRevenueValue: 54.28,
    transactionCount: "6,000",
    rechargeCount: "6,000",
    refundCount: "6,000",
    refundRate: "3.1%",
  },
  {
    id: "free-zone",
    userTypeKey: "freeZone",
    totalRevenue: "32.13M",
    totalRevenueValue: 32.13,
    transactionCount: "5,000",
    rechargeCount: "5,000",
    refundCount: "5,000",
    refundRate: "4.2%",
  },
  {
    id: "embassy",
    userTypeKey: "embassy",
    totalRevenue: "27.28M",
    totalRevenueValue: 27.28,
    transactionCount: "4,000",
    rechargeCount: "4,000",
    refundCount: "4,000",
    refundRate: "3.1%",
  },
  {
    id: "consulate",
    userTypeKey: "consulate",
    totalRevenue: "17.28M",
    totalRevenueValue: 17.28,
    transactionCount: "1,000",
    rechargeCount: "1,000",
    refundCount: "1,000",
    refundRate: "2.3%",
  },
  {
    id: "cultural-clubs",
    userTypeKey: "culturalClubs",
    totalRevenue: "7.28M",
    totalRevenueValue: 7.28,
    transactionCount: "800",
    rechargeCount: "800",
    refundCount: "800",
    refundRate: "2.1%",
  },
  {
    id: "talent-agency",
    userTypeKey: "talentAgency",
    totalRevenue: "1.28M",
    totalRevenueValue: 1.28,
    transactionCount: "25,000",
    rechargeCount: "320",
    refundCount: "100",
    refundRate: "3.2%",
  },
];
