/* eslint-disable @typescript-eslint/no-explicit-any */
import type { TFunction } from 'i18next';
export type TargetType = 'establishment' | 'individual';

export type TaskSearchOption = {
  value: string;
  title: string;
  subtitle: string;
  emirate: string;
  license: string;
  targetType: TargetType;
  payload: Record<string, any>;
};

export const duplicateWarningReasonKeys = [
  'repeatedViolationSixMonths',
  'repeatedViolationTwelveMonths',
  'highSeverityViolationDetected',
  'criticalContentViolation',
  'licenseStatusInconsistency',
  'complaintFromPublic',
  'complaintFromAuthority',
  'other',
] as const;

const normalizeTaskOptionKey = (value?: string) => String(value || '')
  .trim()
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '');

const TASK_OPTION_TRANSLATION_KEYS = {
  emirates: {
    abudhabi: 'inspection.tasks.options.emirates.abuDhabi',
    dubai: 'inspection.tasks.options.emirates.dubai',
    sharjah: 'inspection.tasks.options.emirates.sharjah',
    ajman: 'inspection.tasks.options.emirates.ajman',
    rasalkhaimah: 'inspection.tasks.options.emirates.rasAlKhaimah',
    fujairah: 'inspection.tasks.options.emirates.fujairah',
    ummalquwain: 'inspection.tasks.options.emirates.ummAlQuwain',
  },
  establishmentSubtypes: {
    commercial: 'inspection.tasks.options.establishmentSubtypes.commercial',
    freezone: 'inspection.tasks.options.establishmentSubtypes.freeZone',
    talentagency: 'inspection.tasks.options.establishmentSubtypes.talentAgency',
    government: 'inspection.tasks.options.establishmentSubtypes.government',
    embassy: 'inspection.tasks.options.establishmentSubtypes.embassy',
    consulate: 'inspection.tasks.options.establishmentSubtypes.consulate',
    culturalclubs: 'inspection.tasks.options.establishmentSubtypes.culturalClubs',
  },
  areas: {
    khalifacity: 'inspection.tasks.options.areas.khalifaCity',
    alquoz: 'inspection.tasks.options.areas.alQuoz',
    mediacity: 'inspection.tasks.options.areas.mediaCity',
    businessbay: 'inspection.tasks.options.areas.businessBay',
    albateen: 'inspection.tasks.options.areas.alBateen',
    almajaz: 'inspection.tasks.options.areas.alMajaz',
    alnuaimiya: 'inspection.tasks.options.areas.alNuaimiya',
  },
  inspectionMethods: {
    fieldinspection: 'inspection.tasks.options.inspectionMethods.fieldInspection',
    digitalinspection: 'inspection.tasks.options.inspectionMethods.digitalInspection',
  },
  activities: {
    publishingactivity: 'inspection.tasks.options.activities.publishingActivity',
    distributionactivity: 'inspection.tasks.options.activities.distributionActivity',
    mediatrading: 'inspection.tasks.options.activities.mediaTrading',
    digitalmedia: 'inspection.tasks.options.activities.digitalMedia',
    cinema: 'inspection.tasks.options.activities.cinema',
    culturalevents: 'inspection.tasks.options.activities.culturalEvents',
  },
  createdBy: {
    auto: 'inspection.tasks.options.createdBy.autoGenerated',
    batch: 'inspection.tasks.options.createdBy.batchGenerated',
    manual: 'inspection.tasks.options.createdBy.manual',
    followup: 'inspection.tasks.options.createdBy.followUp',
  },
} as const;

const getTranslatedTaskOptionLabel = (
  value: string | undefined,
  t: TFunction,
  translationKey?: string,
) => {
  const safeValue = String(value || '').trim();
  return translationKey ? t(translationKey) : safeValue;
};

export const priorityOptions = ['Critical', 'High', 'Medium', 'Low'];
export const emirateOptions = ['Abu Dhabi', 'Dubai', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'];
export const establishmentSubtypeOptions = ['Commercial', 'Free Zone', 'Talent Agency', 'Government', 'Embassy', 'Consulate', 'Cultural Clubs'];
// Values from /api/admin/inspection/lookup/establishment-sub-types.
export const establishmentSubtypeWithoutLicenseIds = [3, 31, 32, 33];
const establishmentSubtypeWithoutLicenseIdSet = new Set<number>(establishmentSubtypeWithoutLicenseIds);
export const isEstablishmentSubtypeWithoutLicenseId = (subtypeId?: number | null) => (
  typeof subtypeId === 'number' && establishmentSubtypeWithoutLicenseIdSet.has(subtypeId)
);
export const areaOptions = ['Khalifa City', 'Al Quoz', 'Media City', 'Business Bay', 'Al Bateen', 'Al Majaz', 'Al Nuaimiya'];
export const inspectionMethodOptions = ['Field Inspection', 'Digital Inspection'];
export const activityOptions = [
  'Publishing Activity',
  'Distribution Activity',
  'Media Trading',
  'Digital Media',
  'Cinema',
  'Cultural Events',
];
export const creatorOptions = [
  { value: 'AUTO', label: 'Auto Generated' },
  { value: 'BATCH', label: 'Batch Generated' },
  { value: 'MANUAL', label: 'Manual' },
  { value: 'FOLLOW_UP', label: 'Follow-up' },
];
export const inspectorOptions = [
  { id: 'inspector-001', name: 'Ava Khan' },
  { id: 'inspector-002', name: 'Ethan Noor' },
  { id: 'inspector-003', name: 'Mia Rahman' },
  { id: 'inspector-004', name: 'Omar Saeed' },
];

export const establishmentSearchOptions: TaskSearchOption[] = [
  {
    value: 'est-1001',
    title: 'BANDAI NAMCO',
    subtitle: 'Abu Dhabi | NMA-4458',
    emirate: 'Abu Dhabi',
    license: 'NMA-4458',
    targetType: 'establishment',
    payload: {
      establishmentSubType: 'Commercial',
      emirateNameEn: 'Abu Dhabi',
      authorityNameEn: 'Abu Dhabi Authority',
      tradeLicenseNumber: 'NMA-4458',
      establishmentNameEn: 'BANDAI NAMCO',
      region: 'Abu Dhabi',
      area: 'Khalifa City',
      street: 'No. 21, Sheikh Rashid Bin Saeed St',
      activityNameEn: ['Digital Media'],
      inspectionMethod: 'Digital Inspection',
    },
  },
  {
    value: 'est-1002',
    title: 'Emirates Media Corp',
    subtitle: 'Abu Dhabi | NMA-2451',
    emirate: 'Abu Dhabi',
    license: 'NMA-2451',
    targetType: 'establishment',
    payload: {
      establishmentSubType: 'Commercial',
      emirateNameEn: 'Abu Dhabi',
      authorityNameEn: 'Abu Dhabi Authority',
      tradeLicenseNumber: 'NMA-2451',
      establishmentNameEn: 'Emirates Media Corp',
      region: 'Abu Dhabi',
      area: 'Khalifa City',
      street: 'No. 21, Sheikh Rashid Bin Saeed St',
      activityNameEn: ['Publishing Activity'],
      inspectionMethod: 'Field Inspection',
    },
  },
  {
    value: 'est-1003',
    title: 'Abu Dhabi Media',
    subtitle: 'Abu Dhabi | NMA-3302',
    emirate: 'Abu Dhabi',
    license: 'NMA-3302',
    targetType: 'establishment',
    payload: {
      establishmentSubType: 'Commercial',
      emirateNameEn: 'Abu Dhabi',
      authorityNameEn: 'Abu Dhabi Authority',
      tradeLicenseNumber: 'NMA-3302',
      establishmentNameEn: 'Abu Dhabi Media',
      region: 'Abu Dhabi',
      area: 'Khalifa City',
      street: 'No. 21, Sheikh Rashid Bin Saeed St',
      activityNameEn: ['Publishing Activity', 'Digital Media'],
      inspectionMethod: 'Field Inspection',
    },
  },
  {
    value: 'est-1004',
    title: 'Sky Arabia',
    subtitle: 'Dubai | TL-9931',
    emirate: 'Dubai',
    license: 'TL-9931',
    targetType: 'establishment',
    payload: {
      establishmentSubType: 'Commercial',
      emirateNameEn: 'Dubai',
      authorityNameEn: 'Dubai Authority',
      tradeLicenseNumber: 'TL-9931',
      establishmentNameEn: 'Sky Arabia',
      area: 'Business Bay',
      street: 'Office 1402, Bay Square',
      activityNameEn: ['Media Trading'],
      inspectionMethod: 'Field Inspection',
    },
  },
  {
    value: 'est-1005',
    title: 'Embassy Cultural Club',
    subtitle: 'Abu Dhabi | GOV-5005',
    emirate: 'Abu Dhabi',
    license: 'GOV-5005',
    targetType: 'establishment',
    payload: {
      establishmentSubType: 'Embassy',
      emirateNameEn: 'Abu Dhabi',
      establishmentNameEn: 'Embassy Cultural Club',
      region: 'Abu Dhabi',
      area: 'Al Bateen',
      street: 'Diplomatic Area',
      activityNameEn: ['Cultural Events'],
      inspectionMethod: 'Field Inspection',
    },
  },
  {
    value: 'est-1006',
    title: 'Creative Zone Studios',
    subtitle: 'Dubai | FZ-2044',
    emirate: 'Dubai',
    license: 'FZ-2044',
    targetType: 'establishment',
    payload: {
      establishmentSubType: 'Free Zone',
      emirateNameEn: 'Dubai',
      authorityNameEn: 'Dubai Authority',
      tradeLicenseNumber: 'FZ-2044',
      establishmentNameEn: 'Creative Zone Studios',
      area: 'Media City',
      street: 'Building 8, Dubai Media City',
      activityNameEn: ['Digital Media', 'Publishing Activity'],
      inspectionMethod: 'Digital Inspection',
    },
  },
  {
    value: 'est-1007',
    title: 'Pearl Talent Agency',
    subtitle: 'Sharjah | TA-1180',
    emirate: 'Sharjah',
    license: 'TA-1180',
    targetType: 'establishment',
    payload: {
      establishmentSubType: 'Talent Agency',
      emirateNameEn: 'Sharjah',
      authorityNameEn: 'Sharjah Authority',
      tradeLicenseNumber: 'TA-1180',
      establishmentNameEn: 'Pearl Talent Agency',
      area: 'Al Majaz',
      street: 'Corniche Street, Tower B',
      activityNameEn: ['Digital Media'],
      inspectionMethod: 'Field Inspection',
    },
  },
  {
    value: 'est-1008',
    title: 'Ajman Government Media Office',
    subtitle: 'Ajman | Government',
    emirate: 'Ajman',
    license: 'GOV-AJM',
    targetType: 'establishment',
    payload: {
      establishmentSubType: 'Government',
      emirateNameEn: 'Ajman',
      establishmentNameEn: 'Ajman Government Media Office',
      area: 'Al Nuaimiya',
      street: 'Government District',
      activityNameEn: ['Publishing Activity'],
      inspectionMethod: 'Digital Inspection',
    },
  },
  {
    value: 'est-1009',
    title: 'French Consulate Media Desk',
    subtitle: 'Dubai | Consulate',
    emirate: 'Dubai',
    license: 'CON-DXB',
    targetType: 'establishment',
    payload: {
      establishmentSubType: 'Consulate',
      emirateNameEn: 'Dubai',
      establishmentNameEn: 'French Consulate Media Desk',
      area: 'Al Quoz',
      street: 'Consulate Compound',
      activityNameEn: ['Cultural Events'],
      inspectionMethod: 'Field Inspection',
    },
  },
];

export const individualSearchOptions: TaskSearchOption[] = [
  {
    value: 'ind-2001',
    title: 'Nadia Al-Tamimi',
    subtitle: 'Dubai | EID-7830',
    emirate: 'Dubai',
    license: 'EID-7830',
    targetType: 'individual',
    payload: {
      eid: '784-1988-1234567-1',
      fullName: 'Nadia Al-Tamimi',
      email: 'nadia.altamimi@example.com',
      mobileNumber: '50 123 4567',
      inspectionMethod: 'Digital Inspection',
    },
  },
  {
    value: 'ind-2002',
    title: 'Rashed Noor',
    subtitle: 'Abu Dhabi | EID-5532',
    emirate: 'Abu Dhabi',
    license: 'EID-5532',
    targetType: 'individual',
    payload: {
      eid: '784-1990-7654321-2',
      fullName: 'Rashed Noor',
      email: 'rashed.noor@example.com',
      mobileNumber: '52 555 0188',
      inspectionMethod: 'Field Inspection',
    },
  },
  {
    value: 'ind-2003',
    title: 'Mariam Hassan',
    subtitle: 'Sharjah | EID-4421 | @mariam.media',
    emirate: 'Sharjah',
    license: 'EID-4421',
    targetType: 'individual',
    payload: {
      eid: '784-1994-3322110-3',
      fullName: 'Mariam Hassan',
      email: 'mariam.hassan@example.com',
      mobileNumber: '55 234 1199',
      inspectionMethod: 'Digital Inspection',
    },
  },
  {
    value: 'ind-2004',
    title: 'Yousef Khalid',
    subtitle: 'Abu Dhabi | ML-6620 | Media License',
    emirate: 'Abu Dhabi',
    license: 'ML-6620',
    targetType: 'individual',
    payload: {
      eid: '784-1985-9988776-4',
      fullName: 'Yousef Khalid',
      email: 'yousef.khalid@example.com',
      mobileNumber: '56 778 2450',
      inspectionMethod: 'Field Inspection',
    },
  },
];

export const getAuthorityOptions = (emirate?: string) => {
  const safeEmirate = emirate || 'Abu Dhabi';
  return [`${safeEmirate} Authority`, `${safeEmirate} Department of Economic Development`];
};

export const getInspectionTaskEmirateTranslationKey = (value?: string) =>
  TASK_OPTION_TRANSLATION_KEYS.emirates[normalizeTaskOptionKey(value) as keyof typeof TASK_OPTION_TRANSLATION_KEYS.emirates];

export const getInspectionTaskEstablishmentSubtypeTranslationKey = (value?: string) =>
  TASK_OPTION_TRANSLATION_KEYS.establishmentSubtypes[
    normalizeTaskOptionKey(value) as keyof typeof TASK_OPTION_TRANSLATION_KEYS.establishmentSubtypes
  ];

export const getInspectionTaskAreaTranslationKey = (value?: string) =>
  TASK_OPTION_TRANSLATION_KEYS.areas[normalizeTaskOptionKey(value) as keyof typeof TASK_OPTION_TRANSLATION_KEYS.areas];

export const getInspectionTaskInspectionMethodTranslationKey = (value?: string) =>
  TASK_OPTION_TRANSLATION_KEYS.inspectionMethods[
    normalizeTaskOptionKey(value) as keyof typeof TASK_OPTION_TRANSLATION_KEYS.inspectionMethods
  ];

export const getInspectionTaskActivityTranslationKey = (value?: string) =>
  TASK_OPTION_TRANSLATION_KEYS.activities[normalizeTaskOptionKey(value) as keyof typeof TASK_OPTION_TRANSLATION_KEYS.activities];

export const getInspectionTaskCreatorTranslationKey = (value?: string) =>
  TASK_OPTION_TRANSLATION_KEYS.createdBy[normalizeTaskOptionKey(value) as keyof typeof TASK_OPTION_TRANSLATION_KEYS.createdBy];

export const getInspectionTaskEmirateLabel = (value: string | undefined, t: TFunction) =>
  getTranslatedTaskOptionLabel(value, t, getInspectionTaskEmirateTranslationKey(value));

export const getInspectionTaskEstablishmentSubtypeLabel = (value: string | undefined, t: TFunction) =>
  getTranslatedTaskOptionLabel(value, t, getInspectionTaskEstablishmentSubtypeTranslationKey(value));

export const getInspectionTaskAreaLabel = (value: string | undefined, t: TFunction) =>
  getTranslatedTaskOptionLabel(value, t, getInspectionTaskAreaTranslationKey(value));

export const getInspectionTaskInspectionMethodLabel = (value: string | undefined, t: TFunction) =>
  getTranslatedTaskOptionLabel(value, t, getInspectionTaskInspectionMethodTranslationKey(value));

export const getInspectionTaskActivityLabel = (value: string | undefined, t: TFunction) =>
  getTranslatedTaskOptionLabel(value, t, getInspectionTaskActivityTranslationKey(value));

export const getInspectionTaskCreatorLabel = (value: string | undefined, t: TFunction) =>
  getTranslatedTaskOptionLabel(value, t, getInspectionTaskCreatorTranslationKey(value));

export const getInspectionTaskAuthorityLabel = (value: string | undefined, t: TFunction) => {
  const safeValue = String(value || '').trim();
  if (!safeValue) return '';

  if (safeValue.endsWith(' Authority')) {
    const emirate = safeValue.replace(/ Authority$/, '').trim();
    return t('inspection.tasks.options.authorities.authority', {
      emirate: getInspectionTaskEmirateLabel(emirate, t) || emirate,
    });
  }

  if (safeValue.endsWith(' Department of Economic Development')) {
    const emirate = safeValue.replace(/ Department of Economic Development$/, '').trim();
    return t('inspection.tasks.options.authorities.departmentOfEconomicDevelopment', {
      emirate: getInspectionTaskEmirateLabel(emirate, t) || emirate,
    });
  }

  return safeValue;
};

export const getPriorityId = (value?: string) => {
  if (value === 'Critical') return 1;
  if (value === 'High') return 2;
  if (value === 'Medium') return 3;
  return 4;
};

export const getPriorityNameById = (value?: number | string) => {
  const normalized = Number(value);
  if (normalized === 1) return 'Critical';
  if (normalized === 2) return 'High';
  if (normalized === 3) return 'Medium';
  return 'Low';
};

export const getEmirateId = (value?: string) => {
  const index = emirateOptions.findIndex((item) => item === value);
  return index >= 0 ? index + 1 : 1;
};
