import type { CountryDialCodeOption } from "./types";

export const DEFAULT_COUNTRY_DIAL_CODE = "+971";
type CountryDialCodeOptionSource = Omit<
  CountryDialCodeOption,
  "abbreviation"
>;
const COUNTRY_ABBREVIATION_OVERRIDES: Record<string, string> = {
  ARE: "UAE",
  BIH: "BiH",
  CAF: "CAR",
  COD: "DRC",
  GBR: "UK",
  KOR: "ROK",
  PRK: "DPRK",
  SAU: "KSA",
  VGB: "BVI",
  VIR: "USVI",
  ZAF: "RSA",
};
const COUNTRY_DIAL_CODE_OPTION_SOURCES: CountryDialCodeOptionSource[] = [
  {
    label: "United States",
    labelAr: "الولايات المتحدة",
    value: "+1",
    countryCode: "USA",
  },
  {
    label: "Antigua & Barbuda",
    labelAr: "أنتيغوا وبربودا",
    value: "+1268",
    countryCode: "ATG",
  },
  { label: "Anguilla", labelAr: "أنغويلا", value: "+1264", countryCode: "AIA" },
  {
    label: "American Samoa",
    labelAr: "ساموا الأمريكية",
    value: "+1684",
    countryCode: "ASM",
  },
  { label: "Barbados", labelAr: "بربادوس", value: "+1246", countryCode: "BRB" },
  { label: "Bermuda", labelAr: "برمودا", value: "+1441", countryCode: "BMU" },
  { label: "Bahamas", labelAr: "جزر البهاما", value: "+1242", countryCode: "BHS" },
  { label: "Canada", labelAr: "كندا", value: "+1", countryCode: "CAN" },
  { label: "Dominica", labelAr: "دومينيكا", value: "+1767", countryCode: "DMA" },
  {
    label: "Dominican Republic",
    labelAr: "جمهورية الدومينيكان",
    value: "+1",
    countryCode: "DOM",
  },
  { label: "Grenada", labelAr: "غرينادا", value: "+1473", countryCode: "GRD" },
  { label: "Guam", labelAr: "غوام", value: "+1671", countryCode: "GUM" },
  { label: "Jamaica", labelAr: "جامايكا", value: "+1", countryCode: "JAM" },
  {
    label: "St. Kitts & Nevis",
    labelAr: "سانت كيتس ونيفيس",
    value: "+1869",
    countryCode: "KNA",
  },
  {
    label: "Cayman Islands",
    labelAr: "جزر كايمان",
    value: "+1345",
    countryCode: "CYM",
  },
  { label: "St. Lucia", labelAr: "سانت لوسيا", value: "+1758", countryCode: "LCA" },
  {
    label: "Northern Mariana Islands",
    labelAr: "جزر ماريانا الشمالية",
    value: "+1670",
    countryCode: "MNP",
  },
  { label: "Montserrat", labelAr: "مونتسرات", value: "+1664", countryCode: "MSR" },
  {
    label: "Puerto Rico",
    labelAr: "بورتوريكو",
    value: "+1",
    countryCode: "PRI",
  },
  {
    label: "Sint Maarten",
    labelAr: "سانت مارتن",
    value: "+1721",
    countryCode: "SXM",
  },
  {
    label: "Turks & Caicos Islands",
    labelAr: "جزر توركس وكايكوس",
    value: "+1649",
    countryCode: "TCA",
  },
  {
    label: "Trinidad & Tobago",
    labelAr: "ترينيداد وتوباغو",
    value: "+1868",
    countryCode: "TTO",
  },
  {
    label: "St. Vincent & Grenadines",
    labelAr: "سانت فنسنت وجزر غرينادين",
    value: "+1784",
    countryCode: "VCT",
  },
  {
    label: "British Virgin Islands",
    labelAr: "جزر فيرجن البريطانية",
    value: "+1284",
    countryCode: "VGB",
  },
  {
    label: "U.S. Virgin Islands",
    labelAr: "جزر فيرجن الأمريكية",
    value: "+1340",
    countryCode: "VIR",
  },
  { label: "Russia", labelAr: "روسيا", value: "+7", countryCode: "RUS" },
  { label: "Kazakhstan", labelAr: "كازاخستان", value: "+7", countryCode: "KAZ" },
  { label: "Egypt", labelAr: "مصر", value: "+20", countryCode: "EGY" },
  {
    label: "South Africa",
    labelAr: "جنوب أفريقيا",
    value: "+27",
    countryCode: "ZAF",
  },
  { label: "Greece", labelAr: "اليونان", value: "+30", countryCode: "GRC" },
  { label: "Netherlands", labelAr: "هولندا", value: "+31", countryCode: "NLD" },
  { label: "Belgium", labelAr: "بلجيكا", value: "+32", countryCode: "BEL" },
  { label: "France", labelAr: "فرنسا", value: "+33", countryCode: "FRA" },
  { label: "Spain", labelAr: "إسبانيا", value: "+34", countryCode: "ESP" },
  { label: "Hungary", labelAr: "هنغاريا", value: "+36", countryCode: "HUN" },
  { label: "Italy", labelAr: "إيطاليا", value: "+39", countryCode: "ITA" },
  {
    label: "Vatican City",
    labelAr: "الفاتيكان",
    value: "+39",
    countryCode: "VAT",
  },
  { label: "Romania", labelAr: "رومانيا", value: "+40", countryCode: "ROU" },
  { label: "Switzerland", labelAr: "سويسرا", value: "+41", countryCode: "CHE" },
  { label: "Austria", labelAr: "النمسا", value: "+43", countryCode: "AUT" },
  {
    label: "United Kingdom",
    labelAr: "المملكة المتحدة",
    value: "+44",
    countryCode: "GBR",
  },
  { label: "Guernsey", labelAr: "غيرنزي", value: "+44", countryCode: "GGY" },
  {
    label: "Isle of Man",
    labelAr: "جزيرة مان",
    value: "+44",
    countryCode: "IMN",
  },
  { label: "Jersey", labelAr: "جيرسي", value: "+44", countryCode: "JEY" },
  { label: "Denmark", labelAr: "الدانمرك", value: "+45", countryCode: "DNK" },
  { label: "Sweden", labelAr: "السويد", value: "+46", countryCode: "SWE" },
  { label: "Norway", labelAr: "النرويج", value: "+47", countryCode: "NOR" },
  {
    label: "Svalbard & Jan Mayen",
    labelAr: "سفالبارد وجان ماين",
    value: "+47",
    countryCode: "SJM",
  },
  { label: "Poland", labelAr: "بولندا", value: "+48", countryCode: "POL" },
  { label: "Germany", labelAr: "ألمانيا", value: "+49", countryCode: "DEU" },
  { label: "Peru", labelAr: "بيرو", value: "+51", countryCode: "PER" },
  { label: "Mexico", labelAr: "المكسيك", value: "+52", countryCode: "MEX" },
  { label: "Cuba", labelAr: "كوبا", value: "+53", countryCode: "CUB" },
  { label: "Argentina", labelAr: "الأرجنتين", value: "+54", countryCode: "ARG" },
  { label: "Brazil", labelAr: "البرازيل", value: "+55", countryCode: "BRA" },
  { label: "Chile", labelAr: "تشيلي", value: "+56", countryCode: "CHL" },
  { label: "Colombia", labelAr: "كولومبيا", value: "+57", countryCode: "COL" },
  { label: "Venezuela", labelAr: "فنزويلا", value: "+58", countryCode: "VEN" },
  { label: "Malaysia", labelAr: "ماليزيا", value: "+60", countryCode: "MYS" },
  { label: "Australia", labelAr: "أستراليا", value: "+61", countryCode: "AUS" },
  {
    label: "Cocos (Keeling) Islands",
    labelAr: "جزر كوكوس (كيلينغ)",
    value: "+61",
    countryCode: "CCK",
  },
  {
    label: "Christmas Island",
    labelAr: "جزيرة كريسماس",
    value: "+61",
    countryCode: "CXR",
  },
  { label: "Indonesia", labelAr: "إندونيسيا", value: "+62", countryCode: "IDN" },
  { label: "Philippines", labelAr: "الفلبين", value: "+63", countryCode: "PHL" },
  {
    label: "New Zealand",
    labelAr: "نيوزيلندا",
    value: "+64",
    countryCode: "NZL",
  },
  { label: "Singapore", labelAr: "سنغافورة", value: "+65", countryCode: "SGP" },
  { label: "Thailand", labelAr: "تايلاند", value: "+66", countryCode: "THA" },
  { label: "Japan", labelAr: "اليابان", value: "+81", countryCode: "JPN" },
  {
    label: "South Korea",
    labelAr: "كوريا الجنوبية",
    value: "+82",
    countryCode: "KOR",
  },
  { label: "Vietnam", labelAr: "فيتنام", value: "+84", countryCode: "VNM" },
  { label: "China", labelAr: "الصين", value: "+86", countryCode: "CHN" },
  { label: "Türkiye", labelAr: "تركيا", value: "+90", countryCode: "TUR" },
  { label: "India", labelAr: "الهند", value: "+91", countryCode: "IND" },
  { label: "Pakistan", labelAr: "باكستان", value: "+92", countryCode: "PAK" },
  {
    label: "Afghanistan",
    labelAr: "أفغانستان",
    value: "+93",
    countryCode: "AFG",
  },
  { label: "Sri Lanka", labelAr: "سريلانكا", value: "+94", countryCode: "LKA" },
  {
    label: "Myanmar (Burma)",
    labelAr: "ميانمار (بورما)",
    value: "+95",
    countryCode: "MMR",
  },
  { label: "Iran", labelAr: "إيران", value: "+98", countryCode: "IRN" },
  {
    label: "South Sudan",
    labelAr: "جنوب السودان",
    value: "+211",
    countryCode: "SSD",
  },
  { label: "Morocco", labelAr: "المغرب", value: "+212", countryCode: "MAR" },
  {
    label: "Western Sahara",
    labelAr: "الصحراء الغربية",
    value: "+212",
    countryCode: "ESH",
  },
  { label: "Algeria", labelAr: "الجزائر", value: "+213", countryCode: "DZA" },
  { label: "Tunisia", labelAr: "تونس", value: "+216", countryCode: "TUN" },
  { label: "Libya", labelAr: "ليبيا", value: "+218", countryCode: "LBY" },
  { label: "Gambia", labelAr: "غامبيا", value: "+220", countryCode: "GMB" },
  { label: "Senegal", labelAr: "السنغال", value: "+221", countryCode: "SEN" },
  {
    label: "Mauritania",
    labelAr: "موريتانيا",
    value: "+222",
    countryCode: "MRT",
  },
  { label: "Mali", labelAr: "مالي", value: "+223", countryCode: "MLI" },
  { label: "Guinea", labelAr: "غينيا", value: "+224", countryCode: "GIN" },
  {
    label: "Côte d’Ivoire",
    labelAr: "ساحل العاج",
    value: "+225",
    countryCode: "CIV",
  },
  {
    label: "Burkina Faso",
    labelAr: "بوركينا فاسو",
    value: "+226",
    countryCode: "BFA",
  },
  { label: "Niger", labelAr: "النيجر", value: "+227", countryCode: "NER" },
  { label: "Togo", labelAr: "توغو", value: "+228", countryCode: "TGO" },
  { label: "Benin", labelAr: "بنين", value: "+229", countryCode: "BEN" },
  { label: "Mauritius", labelAr: "موريشيوس", value: "+230", countryCode: "MUS" },
  { label: "Liberia", labelAr: "ليبيريا", value: "+231", countryCode: "LBR" },
  {
    label: "Sierra Leone",
    labelAr: "سيراليون",
    value: "+232",
    countryCode: "SLE",
  },
  { label: "Ghana", labelAr: "غانا", value: "+233", countryCode: "GHA" },
  { label: "Nigeria", labelAr: "نيجيريا", value: "+234", countryCode: "NGA" },
  { label: "Chad", labelAr: "تشاد", value: "+235", countryCode: "TCD" },
  {
    label: "Central African Republic",
    labelAr: "جمهورية أفريقيا الوسطى",
    value: "+236",
    countryCode: "CAF",
  },
  { label: "Cameroon", labelAr: "الكاميرون", value: "+237", countryCode: "CMR" },
  {
    label: "Cape Verde",
    labelAr: "الرأس الأخضر",
    value: "+238",
    countryCode: "CPV",
  },
  {
    label: "São Tomé & Príncipe",
    labelAr: "ساو تومي وبرينسيبي",
    value: "+239",
    countryCode: "STP",
  },
  {
    label: "Equatorial Guinea",
    labelAr: "غينيا الاستوائية",
    value: "+240",
    countryCode: "GNQ",
  },
  { label: "Gabon", labelAr: "الغابون", value: "+241", countryCode: "GAB" },
  {
    label: "Congo - Brazzaville",
    labelAr: "الكونغو - برازافيل",
    value: "+242",
    countryCode: "COG",
  },
  {
    label: "Congo - Kinshasa",
    labelAr: "الكونغو - كينشاسا",
    value: "+243",
    countryCode: "COD",
  },
  { label: "Angola", labelAr: "أنغولا", value: "+244", countryCode: "AGO" },
  {
    label: "Guinea-Bissau",
    labelAr: "غينيا بيساو",
    value: "+245",
    countryCode: "GNB",
  },
  {
    label: "British Indian Ocean Territory",
    labelAr: "الإقليم البريطاني في المحيط الهندي",
    value: "+246",
    countryCode: "IOT",
  },
  {
    label: "Ascension Island",
    labelAr: "جزيرة أسينشيون",
    value: "+247",
    countryCode: "ASC",
  },
  { label: "Seychelles", labelAr: "سيشل", value: "+248", countryCode: "SYC" },
  { label: "Sudan", labelAr: "السودان", value: "+249", countryCode: "SDN" },
  { label: "Rwanda", labelAr: "رواندا", value: "+250", countryCode: "RWA" },
  { label: "Ethiopia", labelAr: "إثيوبيا", value: "+251", countryCode: "ETH" },
  { label: "Somalia", labelAr: "الصومال", value: "+252", countryCode: "SOM" },
  { label: "Djibouti", labelAr: "جيبوتي", value: "+253", countryCode: "DJI" },
  { label: "Kenya", labelAr: "كينيا", value: "+254", countryCode: "KEN" },
  { label: "Tanzania", labelAr: "تنزانيا", value: "+255", countryCode: "TZA" },
  { label: "Uganda", labelAr: "أوغندا", value: "+256", countryCode: "UGA" },
  { label: "Burundi", labelAr: "بوروندي", value: "+257", countryCode: "BDI" },
  { label: "Mozambique", labelAr: "موزمبيق", value: "+258", countryCode: "MOZ" },
  { label: "Zambia", labelAr: "زامبيا", value: "+260", countryCode: "ZMB" },
  { label: "Madagascar", labelAr: "مدغشقر", value: "+261", countryCode: "MDG" },
  { label: "Réunion", labelAr: "روينيون", value: "+262", countryCode: "REU" },
  { label: "Mayotte", labelAr: "مايوت", value: "+262", countryCode: "MYT" },
  { label: "Zimbabwe", labelAr: "زيمبابوي", value: "+263", countryCode: "ZWE" },
  { label: "Namibia", labelAr: "ناميبيا", value: "+264", countryCode: "NAM" },
  { label: "Malawi", labelAr: "ملاوي", value: "+265", countryCode: "MWI" },
  { label: "Lesotho", labelAr: "ليسوتو", value: "+266", countryCode: "LSO" },
  { label: "Botswana", labelAr: "بوتسوانا", value: "+267", countryCode: "BWA" },
  { label: "Eswatini", labelAr: "إسواتيني", value: "+268", countryCode: "SWZ" },
  { label: "Comoros", labelAr: "جزر القمر", value: "+269", countryCode: "COM" },
  {
    label: "St. Helena",
    labelAr: "سانت هيلينا",
    value: "+290",
    countryCode: "SHN",
  },
  {
    label: "Tristan da Cunha",
    labelAr: "تريستان دا كونا",
    value: "+290",
    countryCode: "TDC",
  },
  { label: "Eritrea", labelAr: "إريتريا", value: "+291", countryCode: "ERI" },
  { label: "Aruba", labelAr: "أروبا", value: "+297", countryCode: "ABW" },
  {
    label: "Faroe Islands",
    labelAr: "جزر فارو",
    value: "+298",
    countryCode: "FRO",
  },
  { label: "Greenland", labelAr: "غرينلاند", value: "+299", countryCode: "GRL" },
  { label: "Gibraltar", labelAr: "جبل طارق", value: "+350", countryCode: "GIB" },
  { label: "Portugal", labelAr: "البرتغال", value: "+351", countryCode: "PRT" },
  {
    label: "Luxembourg",
    labelAr: "لوكسمبورغ",
    value: "+352",
    countryCode: "LUX",
  },
  { label: "Ireland", labelAr: "أيرلندا", value: "+353", countryCode: "IRL" },
  { label: "Iceland", labelAr: "آيسلندا", value: "+354", countryCode: "ISL" },
  { label: "Albania", labelAr: "ألبانيا", value: "+355", countryCode: "ALB" },
  { label: "Malta", labelAr: "مالطا", value: "+356", countryCode: "MLT" },
  { label: "Cyprus", labelAr: "قبرص", value: "+357", countryCode: "CYP" },
  { label: "Finland", labelAr: "فنلندا", value: "+358", countryCode: "FIN" },
  {
    label: "Åland Islands",
    labelAr: "جزر آلاند",
    value: "+358",
    countryCode: "ALA",
  },
  { label: "Bulgaria", labelAr: "بلغاريا", value: "+359", countryCode: "BGR" },
  { label: "Lithuania", labelAr: "ليتوانيا", value: "+370", countryCode: "LTU" },
  { label: "Latvia", labelAr: "لاتفيا", value: "+371", countryCode: "LVA" },
  { label: "Estonia", labelAr: "إستونيا", value: "+372", countryCode: "EST" },
  { label: "Moldova", labelAr: "مولدوفا", value: "+373", countryCode: "MDA" },
  { label: "Armenia", labelAr: "أرمينيا", value: "+374", countryCode: "ARM" },
  { label: "Belarus", labelAr: "بيلاروس", value: "+375", countryCode: "BLR" },
  { label: "Andorra", labelAr: "أندورا", value: "+376", countryCode: "AND" },
  { label: "Monaco", labelAr: "موناكو", value: "+377", countryCode: "MCO" },
  {
    label: "San Marino",
    labelAr: "سان مارينو",
    value: "+378",
    countryCode: "SMR",
  },
  { label: "Ukraine", labelAr: "أوكرانيا", value: "+380", countryCode: "UKR" },
  { label: "Serbia", labelAr: "صربيا", value: "+381", countryCode: "SRB" },
  {
    label: "Montenegro",
    labelAr: "الجبل الأسود",
    value: "+382",
    countryCode: "MNE",
  },
  { label: "Kosovo", labelAr: "كوسوفو", value: "+383", countryCode: "KOS" },
  { label: "Croatia", labelAr: "كرواتيا", value: "+385", countryCode: "HRV" },
  { label: "Slovenia", labelAr: "سلوفينيا", value: "+386", countryCode: "SVN" },
  {
    label: "Bosnia & Herzegovina",
    labelAr: "البوسنة والهرسك",
    value: "+387",
    countryCode: "BIH",
  },
  {
    label: "North Macedonia",
    labelAr: "مقدونيا الشمالية",
    value: "+389",
    countryCode: "MKD",
  },
  { label: "Czechia", labelAr: "التشيك", value: "+420", countryCode: "CZE" },
  { label: "Slovakia", labelAr: "سلوفاكيا", value: "+421", countryCode: "SVK" },
  {
    label: "Liechtenstein",
    labelAr: "ليختنشتاين",
    value: "+423",
    countryCode: "LIE",
  },
  {
    label: "Falkland Islands",
    labelAr: "جزر فوكلاند",
    value: "+500",
    countryCode: "FLK",
  },
  { label: "Belize", labelAr: "بليز", value: "+501", countryCode: "BLZ" },
  {
    label: "Guatemala",
    labelAr: "غواتيمالا",
    value: "+502",
    countryCode: "GTM",
  },
  {
    label: "El Salvador",
    labelAr: "السلفادور",
    value: "+503",
    countryCode: "SLV",
  },
  { label: "Honduras", labelAr: "هندوراس", value: "+504", countryCode: "HND" },
  {
    label: "Nicaragua",
    labelAr: "نيكاراغوا",
    value: "+505",
    countryCode: "NIC",
  },
  {
    label: "Costa Rica",
    labelAr: "كوستاريكا",
    value: "+506",
    countryCode: "CRI",
  },
  { label: "Panama", labelAr: "بنما", value: "+507", countryCode: "PAN" },
  {
    label: "St. Pierre & Miquelon",
    labelAr: "سان بيير ومكويلون",
    value: "+508",
    countryCode: "SPM",
  },
  { label: "Haiti", labelAr: "هايتي", value: "+509", countryCode: "HTI" },
  { label: "Guadeloupe", labelAr: "غوادلوب", value: "+590", countryCode: "GLP" },
  {
    label: "St. Barthélemy",
    labelAr: "سان بارتليمي",
    value: "+590",
    countryCode: "BLM",
  },
  {
    label: "St. Martin",
    labelAr: "سان مارتن",
    value: "+590",
    countryCode: "MAF",
  },
  { label: "Bolivia", labelAr: "بوليفيا", value: "+591", countryCode: "BOL" },
  { label: "Guyana", labelAr: "غيانا", value: "+592", countryCode: "GUY" },
  { label: "Ecuador", labelAr: "الإكوادور", value: "+593", countryCode: "ECU" },
  {
    label: "French Guiana",
    labelAr: "غويانا الفرنسية",
    value: "+594",
    countryCode: "GUF",
  },
  { label: "Paraguay", labelAr: "باراغواي", value: "+595", countryCode: "PRY" },
  {
    label: "Martinique",
    labelAr: "جزر المارتينيك",
    value: "+596",
    countryCode: "MTQ",
  },
  { label: "Suriname", labelAr: "سورينام", value: "+597", countryCode: "SUR" },
  { label: "Uruguay", labelAr: "أورغواي", value: "+598", countryCode: "URY" },
  { label: "Curaçao", labelAr: "كوراساو", value: "+599", countryCode: "CUW" },
  {
    label: "Caribbean Netherlands",
    labelAr: "هولندا الكاريبية",
    value: "+599",
    countryCode: "BES",
  },
  {
    label: "Timor-Leste",
    labelAr: "تيمور - ليشتي",
    value: "+670",
    countryCode: "TLS",
  },
  {
    label: "Norfolk Island",
    labelAr: "جزيرة نورفولك",
    value: "+672",
    countryCode: "NFK",
  },
  { label: "Brunei", labelAr: "بروناي", value: "+673", countryCode: "BRN" },
  { label: "Nauru", labelAr: "ناورو", value: "+674", countryCode: "NRU" },
  {
    label: "Papua New Guinea",
    labelAr: "بابوا غينيا الجديدة",
    value: "+675",
    countryCode: "PNG",
  },
  { label: "Tonga", labelAr: "تونغا", value: "+676", countryCode: "TON" },
  {
    label: "Solomon Islands",
    labelAr: "جزر سليمان",
    value: "+677",
    countryCode: "SLB",
  },
  { label: "Vanuatu", labelAr: "فانواتو", value: "+678", countryCode: "VUT" },
  { label: "Fiji", labelAr: "فيجي", value: "+679", countryCode: "FJI" },
  { label: "Palau", labelAr: "بالاو", value: "+680", countryCode: "PLW" },
  {
    label: "Wallis & Futuna",
    labelAr: "جزر والس وفوتونا",
    value: "+681",
    countryCode: "WLF",
  },
  {
    label: "Cook Islands",
    labelAr: "جزر كوك",
    value: "+682",
    countryCode: "COK",
  },
  { label: "Niue", labelAr: "نيوي", value: "+683", countryCode: "NIU" },
  { label: "Samoa", labelAr: "ساموا", value: "+685", countryCode: "WSM" },
  { label: "Kiribati", labelAr: "كيريباتي", value: "+686", countryCode: "KIR" },
  {
    label: "New Caledonia",
    labelAr: "كاليدونيا الجديدة",
    value: "+687",
    countryCode: "NCL",
  },
  { label: "Tuvalu", labelAr: "توفالو", value: "+688", countryCode: "TUV" },
  {
    label: "French Polynesia",
    labelAr: "بولينيزيا الفرنسية",
    value: "+689",
    countryCode: "PYF",
  },
  { label: "Tokelau", labelAr: "توكيلاو", value: "+690", countryCode: "TKL" },
  {
    label: "Micronesia",
    labelAr: "ميكرونيزيا",
    value: "+691",
    countryCode: "FSM",
  },
  {
    label: "Marshall Islands",
    labelAr: "جزر مارشال",
    value: "+692",
    countryCode: "MHL",
  },
  {
    label: "North Korea",
    labelAr: "كوريا الشمالية",
    value: "+850",
    countryCode: "PRK",
  },
  {
    label: "Hong Kong SAR China",
    labelAr: "هونغ كونغ الصينية (منطقة إدارية خاصة)",
    value: "+852",
    countryCode: "HKG",
  },
  {
    label: "Macao SAR China",
    labelAr: "منطقة ماكاو الإدارية الخاصة",
    value: "+853",
    countryCode: "MAC",
  },
  { label: "Cambodia", labelAr: "كمبوديا", value: "+855", countryCode: "KHM" },
  { label: "Laos", labelAr: "لاوس", value: "+856", countryCode: "LAO" },
  {
    label: "Bangladesh",
    labelAr: "بنغلاديش",
    value: "+880",
    countryCode: "BGD",
  },
  { label: "Taiwan", labelAr: "تايوان", value: "+886", countryCode: "TWN" },
  {
    label: "Maldives",
    labelAr: "جزر المالديف",
    value: "+960",
    countryCode: "MDV",
  },
  { label: "Lebanon", labelAr: "لبنان", value: "+961", countryCode: "LBN" },
  { label: "Jordan", labelAr: "الأردن", value: "+962", countryCode: "JOR" },
  { label: "Syria", labelAr: "سوريا", value: "+963", countryCode: "SYR" },
  { label: "Iraq", labelAr: "العراق", value: "+964", countryCode: "IRQ" },
  { label: "Kuwait", labelAr: "الكويت", value: "+965", countryCode: "KWT" },
  {
    label: "Saudi Arabia",
    labelAr: "المملكة العربية السعودية",
    value: "+966",
    countryCode: "SAU",
  },
  { label: "Yemen", labelAr: "اليمن", value: "+967", countryCode: "YEM" },
  { label: "Oman", labelAr: "عُمان", value: "+968", countryCode: "OMN" },
  {
    label: "Palestinian Territories",
    labelAr: "الأراضي الفلسطينية",
    value: "+970",
    countryCode: "PSE",
  },
  {
    label: "United Arab Emirates",
    labelAr: "الإمارات العربية المتحدة",
    value: DEFAULT_COUNTRY_DIAL_CODE,
    countryCode: "ARE",
  },
  { label: "Israel", labelAr: "إسرائيل", value: "+972", countryCode: "ISR" },
  { label: "Bahrain", labelAr: "البحرين", value: "+973", countryCode: "BHR" },
  { label: "Qatar", labelAr: "قطر", value: "+974", countryCode: "QAT" },
  { label: "Bhutan", labelAr: "بوتان", value: "+975", countryCode: "BTN" },
  { label: "Mongolia", labelAr: "منغوليا", value: "+976", countryCode: "MNG" },
  { label: "Nepal", labelAr: "نيبال", value: "+977", countryCode: "NPL" },
  {
    label: "Tajikistan",
    labelAr: "طاجيكستان",
    value: "+992",
    countryCode: "TJK",
  },
  {
    label: "Turkmenistan",
    labelAr: "تركمانستان",
    value: "+993",
    countryCode: "TKM",
  },
  {
    label: "Azerbaijan",
    labelAr: "أذربيجان",
    value: "+994",
    countryCode: "AZE",
  },
  { label: "Georgia", labelAr: "جورجيا", value: "+995", countryCode: "GEO" },
  {
    label: "Kyrgyzstan",
    labelAr: "قيرغيزستان",
    value: "+996",
    countryCode: "KGZ",
  },
  {
    label: "Uzbekistan",
    labelAr: "أوزبكستان",
    value: "+998",
    countryCode: "UZB",
  },
];
export const COUNTRY_DIAL_CODE_OPTIONS: CountryDialCodeOption[] =
  COUNTRY_DIAL_CODE_OPTION_SOURCES.map((option) => ({
    ...option,
    abbreviation:
      COUNTRY_ABBREVIATION_OVERRIDES[option.countryCode] || option.countryCode,
  }));
export const COUNTRY_DIAL_CODE_OPTIONS_MAP: ReadonlyMap<
  string,
  CountryDialCodeOption
> = COUNTRY_DIAL_CODE_OPTIONS.reduce((optionsMap, option) => {
  if (!optionsMap.has(option.value)) {
    optionsMap.set(option.value, option);
  }

  return optionsMap;
}, new Map<string, CountryDialCodeOption>());
