export const languageOptions = 
[
  // UN Official Languages
  { label: "Chinese", value: "Chinese" },
  { label: "English", value: "English" },
  { label: "Spanish", value: "Spanish" },
  { label: "French", value: "French" },
  { label: "Arabic", value: "Arabic" },
  { label: "Russian", value: "Russian" },

  // African Languages
  { label: "Afrikaans", value: "Afrikaans" },
  { label: "Amharic", value: "Amharic" },
  { label: "Akan", value: "Akan" },
  { label: "Bambara", value: "Bambara" },
  { label: "Chichewa", value: "Chichewa" },
  { label: "Hausa", value: "Hausa" },
  { label: "Igbo", value: "Igbo" },
  { label: "Kikuyu", value: "Kikuyu" },
  { label: "Luganda", value: "Luganda" },
  { label: "Malagasy", value: "Malagasy" },
  { label: "Oromo", value: "Oromo" },
  { label: "Shona", value: "Shona" },
  { label: "Somali", value: "Somali" },
  { label: "Swahili", value: "Swahili" },
  { label: "Tigrinya", value: "Tigrinya" },
  { label: "Wolof", value: "Wolof" },
  { label: "Yoruba", value: "Yoruba" },
  { label: "Zulu", value: "Zulu" },

  // American Languages
  { label: "Portuguese (Brazil)", value: "Portuguese (Brazil)" },
  { label: "Spanish (Mexico)", value: "Spanish (Mexico)" },
  { label: "English (US)", value: "English (US)" },
  { label: "French (Canada)", value: "French (Canada)" },
  { label: "Quechua", value: "Quechua" },
  { label: "Guarani", value: "Guarani" },
  { label: "Haitian Creole", value: "Haitian Creole" },
  { label: "Spanish (Argentina)", value: "Spanish (Argentina)" },
  { label: "Spanish (Chile)", value: "Spanish (Chile)" },

  // Asian Languages
  { label: "Chinese (Simplified)", value: "Chinese (Simplified)" },
  { label: "Chinese (Traditional)", value: "Chinese (Traditional)" },
  { label: "Japanese", value: "Japanese" },
  { label: "Korean", value: "Korean" },
  { label: "Hindi", value: "Hindi" },
  { label: "Bengali", value: "Bengali" },
  { label: "Telugu", value: "Telugu" },
  { label: "Marathi", value: "Marathi" },
  { label: "Tamil", value: "Tamil" },
  { label: "Urdu", value: "Urdu" },
  { label: "Indonesian", value: "Indonesian" },
  { label: "Malay", value: "Malay" },
  { label: "Thai", value: "Thai" },
  { label: "Vietnamese", value: "Vietnamese" },
  { label: "Filipino", value: "Filipino" },
  { label: "Persian", value: "Persian" },
  { label: "Hebrew", value: "Hebrew" },
  { label: "Turkish", value: "Turkish" },
  { label: "Burmese", value: "Burmese" },
  { label: "Khmer", value: "Khmer" },
  { label: "Nepali", value: "Nepali" },
  { label: "Mongolian", value: "Mongolian" },

  // European Languages
  { label: "English (UK)", value: "English (UK)" },
  { label: "German", value: "German" },
  { label: "Italian", value: "Italian" },
  { label: "Portuguese (Portugal)", value: "Portuguese (Portugal)" },
  { label: "Dutch", value: "Dutch" },
  { label: "Swedish", value: "Swedish" },
  { label: "Norwegian", value: "Norwegian" },
  { label: "Danish", value: "Danish" },
  { label: "Finnish", value: "Finnish" },
  { label: "Polish", value: "Polish" },
  { label: "Czech", value: "Czech" },
  { label: "Hungarian", value: "Hungarian" },
  { label: "Romanian", value: "Romanian" },
  { label: "Greek", value: "Greek" },
  { label: "Bulgarian", value: "Bulgarian" },
  { label: "Ukrainian", value: "Ukrainian" },
  { label: "Serbian", value: "Serbian" },
  { label: "Croatian", value: "Croatian" },
  { label: "Irish", value: "Irish" },
  { label: "Welsh", value: "Welsh" },
  { label: "Icelandic", value: "Icelandic" },

  // Oceanian Languages
  { label: "English (Australia)", value: "English (Australia)" },
  { label: "English (New Zealand)", value: "English (New Zealand)" },
  { label: "Maori", value: "Maori" },
  { label: "Samoan", value: "Samoan" },
  { label: "Fijian", value: "Fijian" },
  { label: "Hawaiian", value: "Hawaiian" }
]
export default languageOptions;