import DOMPurify, { type Config } from "dompurify";

const TOOLTIP_HTML_SANITIZER_CONFIG: Config = {
  ALLOWED_TAGS: [
    "a",
    "abbr",
    "b",
    "blockquote",
    "br",
    "code",
    "del",
    "div",
    "em",
    "figcaption",
    "figure",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "i",
    "img",
    "li",
    "mark",
    "ol",
    "p",
    "pre",
    "s",
    "small",
    "source",
    "span",
    "strong",
    "sub",
    "sup",
    "table",
    "tbody",
    "td",
    "th",
    "thead",
    "tr",
    "u",
    "ul",
    "video",
  ],
  ALLOWED_ATTR: [
    "alt",
    "class",
    "colspan",
    "controls",
    "dir",
    "height",
    "href",
    "lang",
    "loading",
    "loop",
    "muted",
    "playsinline",
    "poster",
    "preload",
    "rel",
    "rowspan",
    "src",
    "title",
    "width",
  ],
  ALLOW_ARIA_ATTR: true,
  ALLOW_DATA_ATTR: false,
  ALLOW_UNKNOWN_PROTOCOLS: false,
};

export function sanitizeTooltipHtml(content: string): string {
  return DOMPurify.sanitize(content, TOOLTIP_HTML_SANITIZER_CONFIG);
}
