export const INSPECTION_DECLARATION_TEMPLATE_FILE_NAME =
  "Declaration and Acknowledgement.pdf";

export const INSPECTION_DECLARATION_TEMPLATE_URL = "/declaration-template.pdf";

export const INSPECTION_DECLARATION_TEMPLATE_PREVIEW_FILE = {
  name: INSPECTION_DECLARATION_TEMPLATE_FILE_NAME,
  url: INSPECTION_DECLARATION_TEMPLATE_URL,
  filePath: INSPECTION_DECLARATION_TEMPLATE_URL,
} as const;
